spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/gami
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    properties:
        hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
            time_zone: UTC
    security:
        user:
            name: admin
            password: admin
    data:
        redis:
            host: localhost
            port: 6379
            password: "" # Nếu Redis có password thì điền vào
            timeout: 6000 # Timeout kết nối (ms)
jwt:
    signerKey: "1g588fp61K3ru1mWsoT900vsoqykoJs63qAzM2917QKkIAf1ff0WwGHvNu3+vmJ7"



